/* 
 * Sqaush Matrix API
 *
 * v1 documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Game
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GameTests
    {
        // TODO uncomment below to declare an instance variable for Game
        //private Game instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Game
            //instance = new Game();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Game
        /// </summary>
        [Test]
        public void GameInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Game
            //Assert.IsInstanceOfType<Game> (instance, "variable 'instance' is a Game");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Devision'
        /// </summary>
        [Test]
        public void DevisionTest()
        {
            // TODO unit test for the property 'Devision'
        }
        /// <summary>
        /// Test the property '_Event'
        /// </summary>
        [Test]
        public void _EventTest()
        {
            // TODO unit test for the property '_Event'
        }
        /// <summary>
        /// Test the property 'Round'
        /// </summary>
        [Test]
        public void RoundTest()
        {
            // TODO unit test for the property 'Round'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'PlayerAPoints'
        /// </summary>
        [Test]
        public void PlayerAPointsTest()
        {
            // TODO unit test for the property 'PlayerAPoints'
        }
        /// <summary>
        /// Test the property 'PlayerBPoints'
        /// </summary>
        [Test]
        public void PlayerBPointsTest()
        {
            // TODO unit test for the property 'PlayerBPoints'
        }
        /// <summary>
        /// Test the property 'PlayerAGames'
        /// </summary>
        [Test]
        public void PlayerAGamesTest()
        {
            // TODO unit test for the property 'PlayerAGames'
        }
        /// <summary>
        /// Test the property 'PlayerBGames'
        /// </summary>
        [Test]
        public void PlayerBGamesTest()
        {
            // TODO unit test for the property 'PlayerBGames'
        }
        /// <summary>
        /// Test the property 'PlayerARating'
        /// </summary>
        [Test]
        public void PlayerARatingTest()
        {
            // TODO unit test for the property 'PlayerARating'
        }
        /// <summary>
        /// Test the property 'PlayerBRating'
        /// </summary>
        [Test]
        public void PlayerBRatingTest()
        {
            // TODO unit test for the property 'PlayerBRating'
        }
        /// <summary>
        /// Test the property 'PlayerARatingAdjustment'
        /// </summary>
        [Test]
        public void PlayerARatingAdjustmentTest()
        {
            // TODO unit test for the property 'PlayerARatingAdjustment'
        }
        /// <summary>
        /// Test the property 'PlayerBRatingAdjustment'
        /// </summary>
        [Test]
        public void PlayerBRatingAdjustmentTest()
        {
            // TODO unit test for the property 'PlayerBRatingAdjustment'
        }
        /// <summary>
        /// Test the property 'MatchId'
        /// </summary>
        [Test]
        public void MatchIdTest()
        {
            // TODO unit test for the property 'MatchId'
        }
        /// <summary>
        /// Test the property 'PlayerA'
        /// </summary>
        [Test]
        public void PlayerATest()
        {
            // TODO unit test for the property 'PlayerA'
        }
        /// <summary>
        /// Test the property 'PlayerB'
        /// </summary>
        [Test]
        public void PlayerBTest()
        {
            // TODO unit test for the property 'PlayerB'
        }

    }

}
