/* 
 * Sqaush Matrix API
 *
 * v1 documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Player
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlayerTests
    {
        // TODO uncomment below to declare an instance variable for Player
        //private Player instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Player
            //instance = new Player();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Player
        /// </summary>
        [Test]
        public void PlayerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Player
            //Assert.IsInstanceOfType<Player> (instance, "variable 'instance' is a Player");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Test]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }
        /// <summary>
        /// Test the property 'GamesAsPlayerA'
        /// </summary>
        [Test]
        public void GamesAsPlayerATest()
        {
            // TODO unit test for the property 'GamesAsPlayerA'
        }
        /// <summary>
        /// Test the property 'GamesAsPlayerB'
        /// </summary>
        [Test]
        public void GamesAsPlayerBTest()
        {
            // TODO unit test for the property 'GamesAsPlayerB'
        }
        /// <summary>
        /// Test the property 'Clubs'
        /// </summary>
        [Test]
        public void ClubsTest()
        {
            // TODO unit test for the property 'Clubs'
        }

    }

}
