# coding: utf-8

# flake8: noqa

"""
    Squash Matrix API

    # Endeavor The squash matrix API enables clubs, players, and regions to own their information, with results being updated weekly. The API information sits ontop of squash matrix australia website [https://squashmatrix.com](https://squashmatrix.com) # API Aside from the documentation provided below, there is also a `{json:api}` available and can be accessed in the same manner, with the addition of the accept header `{accept: application/vnd.api+json}`. More information about json api can be viewed on their website at [http://jsonapi.org/](http://jsonapi.org/) # Squash Matrix Scrapper There is a ruby SDK for retrieving information from [https://squashmatrix.com](https://squashmatrix.com) which can be found at https://rubygems.org/gems/squash_matrix # SDK's Please stay posted! Client sdk's for the following will be provided shortly:    - Javascript   - Java   - Ruby  # Blog Find relevent and interesting media on [wilkosz.com.au](http://wilkosz.com.au) # Contact Join this endeavor and be appart of the community [https://www.facebook.com/squashmatrixapi](https://www.facebook.com/squashmatrixapi) <hr />  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from SquashMatrixClientAPI.default_api import DefaultApi

# import ApiClient
from SquashMatrixAPI.api_client import ApiClient
from SquashMatrixAPI.configuration import Configuration
# import models into sdk package
from SquashMatrixAPI.SquashMatrixClientModel.api_response_errors import ApiResponseErrors
from SquashMatrixAPI.SquashMatrixClientModel.api_response_errors_errors import ApiResponseErrorsErrors
from SquashMatrixAPI.SquashMatrixClientModel.club import Club
from SquashMatrixAPI.SquashMatrixClientModel.game import Game
from SquashMatrixAPI.SquashMatrixClientModel.inline_response_200 import InlineResponse200
from SquashMatrixAPI.SquashMatrixClientModel.inline_response_200_1 import InlineResponse2001
from SquashMatrixAPI.SquashMatrixClientModel.inline_response_200_2 import InlineResponse2002
from SquashMatrixAPI.SquashMatrixClientModel.inline_response_200_3 import InlineResponse2003
from SquashMatrixAPI.SquashMatrixClientModel.inline_response_200_4 import InlineResponse2004
from SquashMatrixAPI.SquashMatrixClientModel.inline_response_200_5 import InlineResponse2005
from SquashMatrixAPI.SquashMatrixClientModel.player import Player
