# coding: utf-8

"""
    Squash Matrix API

    # Endeavor The squash matrix API enables clubs, players, and regions to own their information, with results being updated weekly. The API information sits ontop of squash matrix australia website [https://squashmatrix.com](https://squashmatrix.com) # API Aside from the documentation provided below, there is also a `{json:api}` available and can be accessed in the same manner, with the addition of the accept header `{accept: application/vnd.api+json}`. More information about json api can be viewed on their website at [http://jsonapi.org/](http://jsonapi.org/) # Squash Matrix Scrapper There is a ruby SDK for retrieving information from [https://squashmatrix.com](https://squashmatrix.com) which can be found at https://rubygems.org/gems/squash_matrix # SDK's Please stay posted! Client sdk's for the following will be provided shortly:    - Javascript   - Java   - Ruby  # Blog Find relevent and interesting media on [wilkosz.com.au](http://wilkosz.com.au) # Contact Join this endeavor and be appart of the community [https://www.facebook.com/squashmatrixapi](https://www.facebook.com/squashmatrixapi) <hr />  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import SquashMatrixAPI
from SquashMatrixClientAPI.default_api import DefaultApi  # noqa: E501
from SquashMatrixAPI.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = SquashMatrixClientAPI.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clubs_get(self):
        """Test case for clubs_get

        Get page of clubs  # noqa: E501
        """
        pass

    def test_clubs_squash_matrix_id_get(self):
        """Test case for clubs_squash_matrix_id_get

        Get club by Squash Matrix ID  # noqa: E501
        """
        pass

    def test_games_game_id_get(self):
        """Test case for games_game_id_get

        Get game by ID  # noqa: E501
        """
        pass

    def test_games_get(self):
        """Test case for games_get

        Get page of games  # noqa: E501
        """
        pass

    def test_players_get(self):
        """Test case for players_get

        Get page of players  # noqa: E501
        """
        pass

    def test_players_squash_matrix_id_get(self):
        """Test case for players_squash_matrix_id_get

        Get player by Squash Matrix ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
