=begin
#Squash Matrix API

## Endeavor The squash matrix API enables clubs, players, and regions to own their information, with results being updated weekly. The API information sits ontop of squash matrix australia website [https://squashmatrix.com](https://squashmatrix.com) # API Aside from the documentation provided below, there is also a `{json:api}` available and can be accessed in the same manner, with the addition of the accept header `{accept: application/vnd.api+json}`. More information about json api can be viewed on their website at [http://jsonapi.org/](http://jsonapi.org/) # Squash Matrix Scrapper There is a ruby SDK for retrieving information from [https://squashmatrix.com](https://squashmatrix.com) which can be found at https://rubygems.org/gems/squash_matrix # SDK's Please stay posted! Client sdk's for the following will be provided shortly:    - Javascript   - Java   - Ruby  # Blog Find relevent and interesting media on [wilkosz.com.au](http://wilkosz.com.au) # Contact Join this endeavor and be appart of the community [https://www.facebook.com/squashmatrixapi](https://www.facebook.com/squashmatrixapi) <hr />

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'squash_matrix_api/api_client'
require 'squash_matrix_api/api_error'
require 'squash_matrix_api/version'
require 'squash_matrix_api/configuration'

# Models
require 'squash_matrix_api/models/api_response_errors'
require 'squash_matrix_api/models/api_response_errors_errors'
require 'squash_matrix_api/models/club'
require 'squash_matrix_api/models/game'
require 'squash_matrix_api/models/inline_response_200'
require 'squash_matrix_api/models/inline_response_200_1'
require 'squash_matrix_api/models/inline_response_200_2'
require 'squash_matrix_api/models/inline_response_200_3'
require 'squash_matrix_api/models/inline_response_200_4'
require 'squash_matrix_api/models/inline_response_200_5'
require 'squash_matrix_api/models/player'

# APIs
require 'squash_matrix_api/api/default_api'

module SquashMatrixAPI
  class << self
    # Customize default settings for the SDK using block.
    #   SquashMatrixAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
