/*
 * Sqaush Matrix API
 * v1 documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Club;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClubApi
 */
@Ignore
public class ClubApiTest {

    private final ClubApi api = new ClubApi();

    
    /**
     * Find club by ID
     *
     * Returns a single club if the request has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findClubByIdTest() throws ApiException {
        Long id = null;
        Club response = api.findClubById(id);

        // TODO: test validations
    }
    
    /**
     * All clubs
     *
     * Returns page of clubs if the request has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findClubsTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        List<Club> response = api.findClubs(page, pageSize);

        // TODO: test validations
    }
    
}
