/*
 * Sqaush Matrix API
 * v1 documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Game;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GameApi
 */
@Ignore
public class GameApiTest {

    private final GameApi api = new GameApi();

    
    /**
     * Find game by ID
     *
     * Returns a single game if the request has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findGameByIdTest() throws ApiException {
        Long id = null;
        Game response = api.findGameById(id);

        // TODO: test validations
    }
    
    /**
     * All games
     *
     * Returns page of games if the request has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findGamesTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        List<Game> response = api.findGames(page, pageSize);

        // TODO: test validations
    }
    
}
