/*
 * Sqaush Matrix API
 * v1 documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Player;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlayerApi
 */
@Ignore
public class PlayerApiTest {

    private final PlayerApi api = new PlayerApi();

    
    /**
     * Find player by ID
     *
     * Returns a single player if the request has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findPlayerByIdTest() throws ApiException {
        Long id = null;
        Player response = api.findPlayerById(id);

        // TODO: test validations
    }
    
    /**
     * All Players
     *
     * Returns page of players if the request has access
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findPlayersTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        List<Player> response = api.findPlayers(page, pageSize);

        // TODO: test validations
    }
    
}
