/**
 * Squash Matrix API
 * # Endeavor The squash matrix API enables clubs, players, and regions to own their information, with results being updated weekly. The API information sits ontop of squash matrix australia website [https://squashmatrix.com](https://squashmatrix.com) # API Aside from the documentation provided below, there is also a `{json:api}` available and can be accessed in the same manner, with the addition of the accept header `{accept: application/vnd.api+json}`. More information about json api can be viewed on their website at [http://jsonapi.org/](http://jsonapi.org/) # Squash Matrix Scrapper There is a ruby SDK for retrieving information from [https://squashmatrix.com](https://squashmatrix.com) which can be found at https://rubygems.org/gems/squash_matrix # SDK's Please stay posted! Client sdk's for the following will be provided shortly:    - Javascript   - Java   - Ruby  # Blog Find relevent and interesting media on [wilkosz.com.au](http://wilkosz.com.au) # Contact Join this endeavor and be appart of the community [https://www.facebook.com/squashmatrixapi](https://www.facebook.com/squashmatrixapi) <hr />
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ApiResponseErrorsErrors model module.
* @module SquashMatrixClient/SquashMatrixClientModel/ApiResponseErrorsErrors
* @version 1.0.0
*/
export default class ApiResponseErrorsErrors {
    /**
    * Constructs a new <code>ApiResponseErrorsErrors</code>.
    * @alias module:SquashMatrixClient/SquashMatrixClientModel/ApiResponseErrorsErrors
    * @class
    * @param code {String} 
    * @param detail {String} 
    */

    constructor(code, detail) {
        

        
        

        this['code'] = code;this['detail'] = detail;

        
    }

    /**
    * Constructs a <code>ApiResponseErrorsErrors</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:SquashMatrixClient/SquashMatrixClientModel/ApiResponseErrorsErrors} obj Optional instance to populate.
    * @return {module:SquashMatrixClient/SquashMatrixClientModel/ApiResponseErrorsErrors} The populated <code>ApiResponseErrorsErrors</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiResponseErrorsErrors();

            
            
            

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * @member {String} detail
    */
    detail = undefined;
    /**
    * @member {String} message
    */
    message = undefined;








}


