/**
 * Squash Matrix API
 * # Endeavor The squash matrix API enables clubs, players, and regions to own their information, with results being updated weekly. The API information sits ontop of squash matrix australia website [https://squashmatrix.com](https://squashmatrix.com) # API Aside from the documentation provided below, there is also a `{json:api}` available and can be accessed in the same manner, with the addition of the accept header `{accept: application/vnd.api+json}`. More information about json api can be viewed on their website at [http://jsonapi.org/](http://jsonapi.org/) # Squash Matrix Scrapper There is a ruby SDK for retrieving information from [https://squashmatrix.com](https://squashmatrix.com) which can be found at https://rubygems.org/gems/squash_matrix # SDK's Please stay posted! Client sdk's for the following will be provided shortly:    - Javascript   - Java   - Ruby  # Blog Find relevent and interesting media on [wilkosz.com.au](http://wilkosz.com.au) # Contact Join this endeavor and be appart of the community [https://www.facebook.com/squashmatrixapi](https://www.facebook.com/squashmatrixapi) <hr />
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Game from './Game';





/**
* The Player model module.
* @module SquashMatrixClient/SquashMatrixClientModel/Player
* @version 1.0.0
*/
export default class Player {
    /**
    * Constructs a new <code>Player</code>.
    * @alias module:SquashMatrixClient/SquashMatrixClientModel/Player
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Player</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:SquashMatrixClient/SquashMatrixClientModel/Player} obj Optional instance to populate.
    * @return {module:SquashMatrixClient/SquashMatrixClientModel/Player} The populated <code>Player</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Player();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('games_as_player_a')) {
                obj['games_as_player_a'] = ApiClient.convertToType(data['games_as_player_a'], [Game]);
            }
            if (data.hasOwnProperty('games_as_player_b')) {
                obj['games_as_player_b'] = ApiClient.convertToType(data['games_as_player_b'], [Game]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Number} rating
    */
    rating = undefined;
    /**
    * @member {Array.<module:SquashMatrixClient/SquashMatrixClientModel/Game>} games_as_player_a
    */
    games_as_player_a = undefined;
    /**
    * @member {Array.<module:SquashMatrixClient/SquashMatrixClientModel/Game>} games_as_player_b
    */
    games_as_player_b = undefined;








}


