=begin
#Sqaush Matrix API

#v1 documentation

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

module SwaggerClient
  VERSION = "1.0.0"
end
