=begin
#Sqaush Matrix API

#v1 documentation

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ClubApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClubApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ClubApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClubApi' do
    it 'should create an instance of ClubApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ClubApi)
    end
  end

  # unit tests for find_club_by_id
  # Find club by ID
  # Returns a single club if the request has access
  # @param id ID of club to fetch
  # @param [Hash] opts the optional parameters
  # @return [Club]
  describe 'find_club_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_clubs
  # All clubs
  # Returns page of clubs if the request has access
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page page number
  # @option opts [Integer] :page_size number of results per page
  # @return [Array<Club>]
  describe 'find_clubs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
