=begin
#Squash Matrix API

## Endeavor The squash matrix API enables clubs, players, and regions to own their information, with results being updated weekly. The API information sits ontop of squash matrix australia website [https://squashmatrix.com](https://squashmatrix.com) # API Aside from the documentation provided below, there is also a `{json:api}` available and can be accessed in the same manner, with the addition of the accept header `{accept: application/vnd.api+json}`. More information about json api can be viewed on their website at [http://jsonapi.org/](http://jsonapi.org/) # Squash Matrix Scrapper There is a ruby SDK for retrieving information from [https://squashmatrix.com](https://squashmatrix.com) which can be found at https://rubygems.org/gems/squash_matrix # SDK's Please stay posted! Client sdk's for the following will be provided shortly:    - Javascript   - Java   - Ruby  # Blog Find relevent and interesting media on [wilkosz.com.au](http://wilkosz.com.au) # Contact Join this endeavor and be appart of the community [https://www.facebook.com/squashmatrixapi](https://www.facebook.com/squashmatrixapi) <hr />

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SquashMatrixAPI::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SquashMatrixAPI::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(SquashMatrixAPI::DefaultApi)
    end
  end

  # unit tests for clubs_get
  # Get page of clubs
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of clubs
  # @option opts [Integer] :page_size The size of page
  # @return [InlineResponse200]
  describe 'clubs_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for clubs_squash_matrix_id_get
  # Get club by Squash Matrix ID
  # 
  # @param squash_matrix_id Squash Matrix ID of club
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'clubs_squash_matrix_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for games_game_id_get
  # Get game by ID
  # 
  # @param game_id Numeric ID of game
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2005]
  describe 'games_game_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for games_get
  # Get page of games
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of games
  # @option opts [Integer] :page_size The size of page
  # @return [InlineResponse2004]
  describe 'games_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for players_get
  # Get page of players
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page of players
  # @option opts [Integer] :page_size The size of page
  # @return [InlineResponse2002]
  describe 'players_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for players_squash_matrix_id_get
  # Get player by Squash Matrix ID
  # 
  # @param squash_matrix_id Squash Matrix ID of player
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2003]
  describe 'players_squash_matrix_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
