=begin
#Sqaush Matrix API

#v1 documentation

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::GameApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GameApi' do
  before do
    # run before each test
    @instance = SwaggerClient::GameApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GameApi' do
    it 'should create an instance of GameApi' do
      expect(@instance).to be_instance_of(SwaggerClient::GameApi)
    end
  end

  # unit tests for find_game_by_id
  # Find game by ID
  # Returns a single game if the request has access
  # @param id ID of game to fetch
  # @param [Hash] opts the optional parameters
  # @return [Game]
  describe 'find_game_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_games
  # All games
  # Returns page of games if the request has access
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page page number
  # @option opts [Integer] :page_size number of results per page
  # @return [Array<Game>]
  describe 'find_games test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
