=begin
#Sqaush Matrix API

#v1 documentation

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PlayerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PlayerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PlayerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlayerApi' do
    it 'should create an instance of PlayerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PlayerApi)
    end
  end

  # unit tests for find_player_by_id
  # Find player by ID
  # Returns a single player if the request has access
  # @param id ID of player to fetch
  # @param [Hash] opts the optional parameters
  # @return [Player]
  describe 'find_player_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_players
  # All Players
  # Returns page of players if the request has access
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page page number
  # @option opts [Integer] :page_size number of results per page
  # @return [Array<Player>]
  describe 'find_players test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
