=begin
#Squash Matrix API

## Endeavor The squash matrix API enables clubs, players, and regions to own their information, with results being updated weekly. The API information sits ontop of squash matrix australia website [https://squashmatrix.com](https://squashmatrix.com) # API Aside from the documentation provided below, there is also a `{json:api}` available and can be accessed in the same manner, with the addition of the accept header `{accept: application/vnd.api+json}`. More information about json api can be viewed on their website at [http://jsonapi.org/](http://jsonapi.org/) # Squash Matrix Scrapper There is a ruby SDK for retrieving information from [https://squashmatrix.com](https://squashmatrix.com) which can be found at https://rubygems.org/gems/squash_matrix # SDK's Please stay posted! Client sdk's for the following will be provided shortly:    - Javascript   - Java   - Ruby  # Blog Find relevent and interesting media on [wilkosz.com.au](http://wilkosz.com.au) # Contact Join this endeavor and be appart of the community [https://www.facebook.com/squashmatrixapi](https://www.facebook.com/squashmatrixapi) <hr />

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module SquashMatrixAPI

  class Game
    attr_accessor :id

    attr_accessor :date

    attr_accessor :division

    attr_accessor :event

    attr_accessor :round

    attr_accessor :position

    attr_accessor :player_a_name

    attr_accessor :player_b_name

    # Player association
    attr_accessor :player_a_id

    # Player association
    attr_accessor :player_b_id

    attr_accessor :player_a_points

    attr_accessor :player_b_points

    attr_accessor :player_a_games

    attr_accessor :player_b_games

    attr_accessor :player_a_rating

    attr_accessor :player_b_rating

    attr_accessor :player_a_rating_adjustment

    attr_accessor :player_b_rating_adjustment

    # Squash Matrix mathch id
    attr_accessor :match_id


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'date' => :'date',
        :'division' => :'division',
        :'event' => :'event',
        :'round' => :'round',
        :'position' => :'position',
        :'player_a_name' => :'player_a_name',
        :'player_b_name' => :'player_b_name',
        :'player_a_id' => :'player_a_id',
        :'player_b_id' => :'player_b_id',
        :'player_a_points' => :'player_a_points',
        :'player_b_points' => :'player_b_points',
        :'player_a_games' => :'player_a_games',
        :'player_b_games' => :'player_b_games',
        :'player_a_rating' => :'player_a_rating',
        :'player_b_rating' => :'player_b_rating',
        :'player_a_rating_adjustment' => :'player_a_rating_adjustment',
        :'player_b_rating_adjustment' => :'player_b_rating_adjustment',
        :'match_id' => :'match_id'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'Integer',
        :'date' => :'Date',
        :'division' => :'String',
        :'event' => :'String',
        :'round' => :'String',
        :'position' => :'String',
        :'player_a_name' => :'String',
        :'player_b_name' => :'String',
        :'player_a_id' => :'Integer',
        :'player_b_id' => :'Integer',
        :'player_a_points' => :'Integer',
        :'player_b_points' => :'Integer',
        :'player_a_games' => :'Integer',
        :'player_b_games' => :'Integer',
        :'player_a_rating' => :'Float',
        :'player_b_rating' => :'Float',
        :'player_a_rating_adjustment' => :'Float',
        :'player_b_rating_adjustment' => :'Float',
        :'match_id' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.has_key?(:'division')
        self.division = attributes[:'division']
      end

      if attributes.has_key?(:'event')
        self.event = attributes[:'event']
      end

      if attributes.has_key?(:'round')
        self.round = attributes[:'round']
      end

      if attributes.has_key?(:'position')
        self.position = attributes[:'position']
      end

      if attributes.has_key?(:'player_a_name')
        self.player_a_name = attributes[:'player_a_name']
      end

      if attributes.has_key?(:'player_b_name')
        self.player_b_name = attributes[:'player_b_name']
      end

      if attributes.has_key?(:'player_a_id')
        self.player_a_id = attributes[:'player_a_id']
      end

      if attributes.has_key?(:'player_b_id')
        self.player_b_id = attributes[:'player_b_id']
      end

      if attributes.has_key?(:'player_a_points')
        self.player_a_points = attributes[:'player_a_points']
      end

      if attributes.has_key?(:'player_b_points')
        self.player_b_points = attributes[:'player_b_points']
      end

      if attributes.has_key?(:'player_a_games')
        self.player_a_games = attributes[:'player_a_games']
      end

      if attributes.has_key?(:'player_b_games')
        self.player_b_games = attributes[:'player_b_games']
      end

      if attributes.has_key?(:'player_a_rating')
        self.player_a_rating = attributes[:'player_a_rating']
      end

      if attributes.has_key?(:'player_b_rating')
        self.player_b_rating = attributes[:'player_b_rating']
      end

      if attributes.has_key?(:'player_a_rating_adjustment')
        self.player_a_rating_adjustment = attributes[:'player_a_rating_adjustment']
      end

      if attributes.has_key?(:'player_b_rating_adjustment')
        self.player_b_rating_adjustment = attributes[:'player_b_rating_adjustment']
      end

      if attributes.has_key?(:'match_id')
        self.match_id = attributes[:'match_id']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          date == o.date &&
          division == o.division &&
          event == o.event &&
          round == o.round &&
          position == o.position &&
          player_a_name == o.player_a_name &&
          player_b_name == o.player_b_name &&
          player_a_id == o.player_a_id &&
          player_b_id == o.player_b_id &&
          player_a_points == o.player_a_points &&
          player_b_points == o.player_b_points &&
          player_a_games == o.player_a_games &&
          player_b_games == o.player_b_games &&
          player_a_rating == o.player_a_rating &&
          player_b_rating == o.player_b_rating &&
          player_a_rating_adjustment == o.player_a_rating_adjustment &&
          player_b_rating_adjustment == o.player_b_rating_adjustment &&
          match_id == o.match_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, date, division, event, round, position, player_a_name, player_b_name, player_a_id, player_b_id, player_a_points, player_b_points, player_a_games, player_b_games, player_a_rating, player_b_rating, player_a_rating_adjustment, player_b_rating_adjustment, match_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SquashMatrixAPI.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
