/*
 * Sqaush Matrix API
 * v1 documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Player;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Game
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-19T07:37:31.189-04:00")
public class Game {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("devision")
  private String devision = null;

  @SerializedName("event")
  private String event = null;

  @SerializedName("round")
  private String round = null;

  @SerializedName("position")
  private String position = null;

  @SerializedName("player_a_points")
  private Integer playerAPoints = null;

  @SerializedName("player_b_points")
  private Integer playerBPoints = null;

  @SerializedName("player_a_games")
  private Integer playerAGames = null;

  @SerializedName("player_b_games")
  private Integer playerBGames = null;

  @SerializedName("player_a_rating")
  private Double playerARating = null;

  @SerializedName("player_b_rating")
  private Double playerBRating = null;

  @SerializedName("player_a_rating_adjustment")
  private Double playerARatingAdjustment = null;

  @SerializedName("player_b_rating_adjustment")
  private Double playerBRatingAdjustment = null;

  @SerializedName("match_id")
  private Integer matchId = null;

  @SerializedName("player_a")
  private Player playerA = null;

  @SerializedName("player_b")
  private Player playerB = null;

  public Game id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Game date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public Game devision(String devision) {
    this.devision = devision;
    return this;
  }

   /**
   * Get devision
   * @return devision
  **/
  @ApiModelProperty(value = "")
  public String getDevision() {
    return devision;
  }

  public void setDevision(String devision) {
    this.devision = devision;
  }

  public Game event(String event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @ApiModelProperty(required = true, value = "")
  public String getEvent() {
    return event;
  }

  public void setEvent(String event) {
    this.event = event;
  }

  public Game round(String round) {
    this.round = round;
    return this;
  }

   /**
   * Get round
   * @return round
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRound() {
    return round;
  }

  public void setRound(String round) {
    this.round = round;
  }

  public Game position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public Game playerAPoints(Integer playerAPoints) {
    this.playerAPoints = playerAPoints;
    return this;
  }

   /**
   * Get playerAPoints
   * @return playerAPoints
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPlayerAPoints() {
    return playerAPoints;
  }

  public void setPlayerAPoints(Integer playerAPoints) {
    this.playerAPoints = playerAPoints;
  }

  public Game playerBPoints(Integer playerBPoints) {
    this.playerBPoints = playerBPoints;
    return this;
  }

   /**
   * Get playerBPoints
   * @return playerBPoints
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPlayerBPoints() {
    return playerBPoints;
  }

  public void setPlayerBPoints(Integer playerBPoints) {
    this.playerBPoints = playerBPoints;
  }

  public Game playerAGames(Integer playerAGames) {
    this.playerAGames = playerAGames;
    return this;
  }

   /**
   * Get playerAGames
   * @return playerAGames
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPlayerAGames() {
    return playerAGames;
  }

  public void setPlayerAGames(Integer playerAGames) {
    this.playerAGames = playerAGames;
  }

  public Game playerBGames(Integer playerBGames) {
    this.playerBGames = playerBGames;
    return this;
  }

   /**
   * Get playerBGames
   * @return playerBGames
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPlayerBGames() {
    return playerBGames;
  }

  public void setPlayerBGames(Integer playerBGames) {
    this.playerBGames = playerBGames;
  }

  public Game playerARating(Double playerARating) {
    this.playerARating = playerARating;
    return this;
  }

   /**
   * Get playerARating
   * @return playerARating
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getPlayerARating() {
    return playerARating;
  }

  public void setPlayerARating(Double playerARating) {
    this.playerARating = playerARating;
  }

  public Game playerBRating(Double playerBRating) {
    this.playerBRating = playerBRating;
    return this;
  }

   /**
   * Get playerBRating
   * @return playerBRating
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getPlayerBRating() {
    return playerBRating;
  }

  public void setPlayerBRating(Double playerBRating) {
    this.playerBRating = playerBRating;
  }

  public Game playerARatingAdjustment(Double playerARatingAdjustment) {
    this.playerARatingAdjustment = playerARatingAdjustment;
    return this;
  }

   /**
   * Get playerARatingAdjustment
   * @return playerARatingAdjustment
  **/
  @ApiModelProperty(value = "")
  public Double getPlayerARatingAdjustment() {
    return playerARatingAdjustment;
  }

  public void setPlayerARatingAdjustment(Double playerARatingAdjustment) {
    this.playerARatingAdjustment = playerARatingAdjustment;
  }

  public Game playerBRatingAdjustment(Double playerBRatingAdjustment) {
    this.playerBRatingAdjustment = playerBRatingAdjustment;
    return this;
  }

   /**
   * Get playerBRatingAdjustment
   * @return playerBRatingAdjustment
  **/
  @ApiModelProperty(value = "")
  public Double getPlayerBRatingAdjustment() {
    return playerBRatingAdjustment;
  }

  public void setPlayerBRatingAdjustment(Double playerBRatingAdjustment) {
    this.playerBRatingAdjustment = playerBRatingAdjustment;
  }

  public Game matchId(Integer matchId) {
    this.matchId = matchId;
    return this;
  }

   /**
   * Get matchId
   * @return matchId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getMatchId() {
    return matchId;
  }

  public void setMatchId(Integer matchId) {
    this.matchId = matchId;
  }

  public Game playerA(Player playerA) {
    this.playerA = playerA;
    return this;
  }

   /**
   * Get playerA
   * @return playerA
  **/
  @ApiModelProperty(required = true, value = "")
  public Player getPlayerA() {
    return playerA;
  }

  public void setPlayerA(Player playerA) {
    this.playerA = playerA;
  }

  public Game playerB(Player playerB) {
    this.playerB = playerB;
    return this;
  }

   /**
   * Get playerB
   * @return playerB
  **/
  @ApiModelProperty(required = true, value = "")
  public Player getPlayerB() {
    return playerB;
  }

  public void setPlayerB(Player playerB) {
    this.playerB = playerB;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Game game = (Game) o;
    return Objects.equals(this.id, game.id) &&
        Objects.equals(this.date, game.date) &&
        Objects.equals(this.devision, game.devision) &&
        Objects.equals(this.event, game.event) &&
        Objects.equals(this.round, game.round) &&
        Objects.equals(this.position, game.position) &&
        Objects.equals(this.playerAPoints, game.playerAPoints) &&
        Objects.equals(this.playerBPoints, game.playerBPoints) &&
        Objects.equals(this.playerAGames, game.playerAGames) &&
        Objects.equals(this.playerBGames, game.playerBGames) &&
        Objects.equals(this.playerARating, game.playerARating) &&
        Objects.equals(this.playerBRating, game.playerBRating) &&
        Objects.equals(this.playerARatingAdjustment, game.playerARatingAdjustment) &&
        Objects.equals(this.playerBRatingAdjustment, game.playerBRatingAdjustment) &&
        Objects.equals(this.matchId, game.matchId) &&
        Objects.equals(this.playerA, game.playerA) &&
        Objects.equals(this.playerB, game.playerB);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, date, devision, event, round, position, playerAPoints, playerBPoints, playerAGames, playerBGames, playerARating, playerBRating, playerARatingAdjustment, playerBRatingAdjustment, matchId, playerA, playerB);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Game {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    devision: ").append(toIndentedString(devision)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    round: ").append(toIndentedString(round)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    playerAPoints: ").append(toIndentedString(playerAPoints)).append("\n");
    sb.append("    playerBPoints: ").append(toIndentedString(playerBPoints)).append("\n");
    sb.append("    playerAGames: ").append(toIndentedString(playerAGames)).append("\n");
    sb.append("    playerBGames: ").append(toIndentedString(playerBGames)).append("\n");
    sb.append("    playerARating: ").append(toIndentedString(playerARating)).append("\n");
    sb.append("    playerBRating: ").append(toIndentedString(playerBRating)).append("\n");
    sb.append("    playerARatingAdjustment: ").append(toIndentedString(playerARatingAdjustment)).append("\n");
    sb.append("    playerBRatingAdjustment: ").append(toIndentedString(playerBRatingAdjustment)).append("\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    playerA: ").append(toIndentedString(playerA)).append("\n");
    sb.append("    playerB: ").append(toIndentedString(playerB)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

